version: '3'

services:
  # app:
  #   build: .
  #   restart: always
  #   command: npm run dev
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - db-net
  #   volumes:
  #     - .:/usr/app

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'database_winest'
    restart: always
    volumes:
      - ./winest-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  winest-db-volume:
