version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'database_winest'
    restart: always
    volumes:
      - ./winest-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  # app:
  #   build: .
  #   restart: always
  #   command: npm start
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://pguser:pgpassword@localhost:5432/winest?schema=public
  #   networks:
  #     - my-network
  #   volumes:
  #     - .:/usr/app

volumes:
  winest-db-volume:

# networks:
#   my-network:
