version: '3.8'

services:
  app:
    build: .
    restart: always
    command: npm run dev
    ports:
      - '3000:3000'
    networks:
      - db-net
    volumes:
      - .:/usr/app

  db:
    container_name: 'database_winest'
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION --explicit_defaults_for_timestamp=1
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
